### ISSUE TITLE
belongs_to and has_one

### ISSUE THREAD

**Issue by gengyabc** [rubysherpas/r4ia_examples#1]
Hello, I am reading rails 4 in action. This is great book. 
I have some question to ask about the code. 

for the `comment` and its `state`, why use
`belongs_to :state`
but not
`has_one :state`

I know there are foreign key issues, here just ignore all other things. I think saying  "a comment has a state" is more suitable than saying "a comment belongs to a state".

Thank you.

**Comment by sevenseacat** [comment]
You can't really ignore the foreign key issue though, because the location of the foreign key is the only difference between `belongs_to` and `has_one`!

It might make more sense to say a comment has a state, but in Rails nomenclature this would mean that the `State` model would have a `comment_id` foreign key - and that's not what we have (nor would that be a good idea, as two comments couldn't have the same state anymore). So we flip the association around - it sounds a little weirder, but it means that the `Comment` model now has the `state_id` field as we expect.

Does this help?

**Comment by gengyabc** [comment]
Yes, it helps. 
Thanks very much. 

After drawing the two tables on paper, I find if use "a comment has a state" way, the table structures are better to be re-designed even besides the foreign key issue. That would make more work to do.
